apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbpostgres
  labels:
    app: dbpostgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbpostgres
  template:
    metadata:
      labels:
        app: dbpostgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "yourusername"
            - name: POSTGRES_PASSWORD
              value: "yourpassword"
            - name: POSTGRES_DB
              value: "shoppingdb"