apiVersion: v1
kind: Service
metadata:
  name: dbpostgres
  labels:
    app: dbpostgres
spec:
  selector:
    app: dbpostgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP